export const BARANGAYS = [
    "Abagon",
    "Amacalan",
    "Apsayan",
    "Ayson",
    "Bawa",
    "Buenlag",
    "Bularit",
    "Calayaan",
    "Carbonel",
    "Cardona",
    "Caturay",
    "Danzo",
    "Dicolor",
    "Don Basilio",
    "Luna",
    "Mabini",
    "Magaspac",
    "Malayep",
    "Matapitap",
    "Matayuncab",
    "New Salem",
    "Oloybuaya",
    "Padapada",
    "Parsolingan",
    "Pinasling",
    "Plastado",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Quezon",
    "Rizal",
    "Salapungan",
    "San Agustin",
    "San Antonio",
    "San Bartolome",
    "San Jose",
    "Santiago",
    "Sembrano",
    "Sta. Lucia",
    "Sulipa",
    "Tagumbao",
    "Tangcaran",
    "Villa Paz",
];
